use app::{app::App, config::{Config, Node}, config_db::ConfigDb};
use eyre::Result;
use util::file_put_contents;



#[derive(clap::Args)]
pub struct Args;


pub async fn action(_args: Args) -> Result<()> {
 
    let pool = ConfigDb::connection_pool().await?;
    let config = Config::new(&pool);
    let mut config_string = String::from("# Auto generated by webman\n\n");

    let active_node_ids = config.active_node_ids().await?;

    let document_root = App::document_root();

    for node_id in active_node_ids{
        
        let node = Node::new(&node_id, &pool);
        let node_data = node.data().await?;
        let ssh_config = node.ssh_config().await?;

        config_string = format!(
            "{config_string}Host {Host}\n    User {User}\n    HostName {HostName}\n    PasswordAuthentication false\n    PubkeyAuthentication true\n    IdentityFile {IdentifyFile}\n\n\n",
            Host = ssh_config.host,
            User = node_data.ssh.username,
            HostName = ssh_config.host_name,
            IdentifyFile = ssh_config.identity_file
        );

    }


    file_put_contents(&format!("{}/.ssh/config", document_root), &config_string);

    println!("SSH config generated!");

    Ok(())

}